### ISSUE TITLE
[bug] Errors when installing Helm chart in KubeFate

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/fate-operator#13]
I am using `config/samples` to create the fatecluster. But the operator enters a live lock and cannot create it successfully.

It creates the cluster then removes it in the next reconciliation.

```
spec:
  clusterSpec:
    chartName: fate
    chartVersion: v1.4.0-a
    istio: {}
    modules:
    - rollsite
    - clustermanager
    - nodemanager
    - mysql
    - python
    - client
    mysql:
      accessMode: ReadWriteOnce
      database: eggroll_meta
      ip: mysql
      nodeSelector: {}
      password: fate_dev
      port: 3306
      size: 1Gi
      storageClass: mysql
      user: fate
    name: fatecluster-sample
    namespace: fate-9999
    nodemanager:
      count: 3
      list:
      - accessMode: ReadWriteOnce
        name: nodemanager
        nodeSelector: {}
        sessionProcessorsPerNode: 2
        size: 1Gi
        storageClass: nodemanager
        subPath: nodemanager
      sessionProcessorsPerNode: 4
    partyId: 9999
    python:
      fateflowNodePort: 30109
      fateflowType: NodePort
      nodeSelector: {}
    rollsite:
      exchange:
        ip: 192.168.1.1
        port: 30000
      nodePort: 30009
      nodeSelector: {}
      partyList:
      - partyId: 10000
        partyIp: 192.168.10.1
        partyPort: 30010
      type: NodePort
    servingIp: 192.168.9.1
    servingPort: 30209
  kubefate:
    name: kubefate-sample
    namespace: kube-fate
status:
  jobId: 6d6703c3-a521-4cf6-a930-f191babe61a9
  clusterId: d57d0daa-5479-4638-ae45-7b6309d2efaf
  status: Creating
```

After a while, the status becomes:

```diff
status:
  status: Creating
```

Logs: https://paste.ubuntu.com/p/MdSj8x7YRH/
