### ISSUE TITLE
[feature request] Use ObjectReference as fateClusterRef

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/fate-operator#5]
We now use `fateClusterRef: fatecluster-sample` to tell the operator that the FateJob is owned by the cluster.

Can we use [ObjectReference](https://kubernetes.github.io/cluster-registry/reference/build/index.html#objectreference-v1alpha1) instead of string for better reuse and supporting FateClusters in other namespaces?

For example:

```yaml
apiVersion: app.kubefate.net/v1beta1
kind: FateJob
metadata:
  name: fatejob-sample
  namespace: fate-9999
spec:
  # FATE cluster deployed in the Org.
  fateClusterRef: 
    name: fatecluster-sample
    namespace: default
    kind: FateCluster
```
